default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  # database: noteapp_development

test:
  <<: *default
  # database: noteapp_test

production:
  <<: *default
  # database: noteapp_production
  # username: noteapp
  # password: <%= ENV['NOTEAPP_DATABASE_PASSWORD'] %>
